# permissions for end users to view keystones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: keystone-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keystone-operator
    app.kubernetes.io/part-of: keystone-operator
    app.kubernetes.io/managed-by: kustomize
  name: keystone-viewer-role
rules:
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystones/status
  verbs:
  - get
