---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keystones.keystone.openstack.org
spec:
  group: keystone.openstack.org
  names:
    kind: Keystone
    listKind: KeystoneList
    plural: keystones
    singular: keystone
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Keystone is the Schema for the keystones API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Keystone
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              role:
                type: string
              keystoneLoggingDebug:
                type: boolean
              keystoneAdminUser:
                type: string
              keystoneAdminProject:
                type: string
              defaultProjectDomainName:
                type: string
              defaultProjectDomainId:
                type: string
              defaultUserDomainName:
                type: string
              defaultUserDomainId:
                type: string
              keystoneTokenProvider:
                type: string
              fernetTokenExpiry:
                type: integer
                format: int32
              fernetTokenAllowExpiredWindow:
                type: integer
                format: int32
              fernetKeyRotationInterval:
                type: integer
                format: int32
              keystoneDefaultUserRole:
                type: string
              keystoneDatabaseName:
                type: string
                description: The database name for keystone
              keystoneDatabaseUser:
                type: string
                description: optional username used for keystone DB
              keystoneUsername:
                type: string
                description: Keystone username used for fernet
              keystoneGroupname:
                type: string
                description: Keystone groupname used for fernet
              region:
                description: Region - optional region name for the keystone service
                type: string
              replicas:
                default: 1
                description: Replicas of keystone API to run
                format: int32
                maximum: 32
                minimum: 0
                type: integer
              resources:
                description: Resources - Compute Resources required by this service
                  (Limits/Requests). https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
                properties:
                  limits:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    description: 'Limits describes the maximum amount of compute resources
                      allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                    type: object
                  requests:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    description: 'Requests describes the minimum amount of compute
                      resources required. If Requests is omitted for a container,
                      it defaults to Limits if that is explicitly specified, otherwise
                      to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                    type: object
                type: object
          status:
            description: Status defines the observed state of Keystone
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
